apiVersion: extensions/v1beta1
kind: Pod
metadata:
  name: {{ template "storm.nimbus.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.nimbus.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "storm.nimbus.fullname" . }}
    spec:
      initContainers:
      - name: init-{{ template "storm.zookeeper.fullname" . }}
        image: busybox
        command: ["sh", "-c", "until nslookup {{ template "storm.zookeeper.fullname" . }}; do echo waiting for {{ template "storm.zookeeper.fullname" . }}; sleep 2; done;"]
      containers:
      - name: {{ .Values.nimbus.service.name }}
        image: "{{ .Values.nimbus.image.repository }}:{{ .Values.nimbus.image.tag }}"
        imagePullPolicy: {{ .Values.nimbus.image.pullPolicy }}
        command: ["storm", "nimbus"]
        ports:
        - containerPort: {{ .Values.nimbus.service.port }}
        resources:
{{ toYaml .Values.nimbus.resources | indent 10 }}
