apiVersion: v1
kind: Service
metadata:
  name: {{ template "storm.nimbus.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  ports:
  - port: {{ .Values.nimbus.service.port }}
    targetPort: {{ .Values.nimbus.service.internalPort }}
    name: {{ .Values.nimbus.service.name }}
  selector:
    app: {{ template "storm.nimbus.fullname" . }}
